# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  - NODE_OPTIONS

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# - task: Npm@1
#   inputs:
#     command: 'install'
#     workingDir: 'src'
# - script: docker build -t turma/dockertest .  # add options to this command to meet your needs
# - task: Docker@2
#   displayName: Login to Docker Hub
#   inputs:
#     command: login
#     containerRegistry: TurmaRepo

- task: Docker@2
  inputs:
    containerRegistry: 'TurmaRepo'
    repository: 'dockertest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
